name    'ivaldi-openup'
version '0.1.0'
author 'frenkel'
license 'BSD'
summary 'Puppet modele to install and run M:Tier openup on OpenBSD'
description 'Puppet modele to install and run M:Tier openup on OpenBSD'
project_page 'https://github.com/frenkel/frenkel-openup'
